GET  http://localhost:3001/info
###
GET  http://localhost:3001/api/persons
###
GET  http://localhost:3001/api/persons/65e885d2b919f04d4dab8449
###
GET  http://localhost:3001/api/persons/10000
###
GET  http://localhost:3001/api/persons/11e885d2b919f04d4dab8449
###
DELETE http://localhost:3001/api/persons/11e885d2b919f04d4dab8449
###
DELETE http://localhost:3001/api/persons/10000

###
POST http://localhost:3001/api/persons
content-type: application/json

{
 "name": "Franck3",
 "number": "39-44-5323523"
}