### Require REST client VSCODE extension

GET  http://localhost:3001/info
###
GET  http://localhost:3001/api/persons
###
GET  http://localhost:3001/api/persons/65e885d2b919f04d4dab8449
###
GET  http://localhost:3001/api/persons/10000
###
GET  http://localhost:3001/api/persons/11e885d2b919f04d4dab8449
###
DELETE http://localhost:3001/api/persons/65e9efa57fb57e7604452b59
###
DELETE http://localhost:3001/api/persons/10000

###
POST http://localhost:3001/api/persons
content-type: application/json

{
 "name": "Franck3",
 "number": "39-44-5323523"
}

###
PUT http://localhost:3001/api/persons/65e9f5f64c6b84fd78851dfa
content-type: application/json

{
 "name": "Franck3",
 "number": "06xxxxxxxx"
}